# Generated by Django 5.0.4 on 2024-04-12 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Имя физического лица',
                'verbose_name_plural': 'Имена физических лиц',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonPatronymic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(max_length=130, unique=True, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Отчество физического лица',
                'verbose_name_plural': 'Отчества физических лиц',
                'ordering': ['patronymic'],
            },
        ),
        migrations.CreateModel(
            name='PersonSurname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=130, unique=True, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Фамилия физического лица',
                'verbose_name_plural': 'Фамилии физических лиц',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonebook.personname', verbose_name='Имя')),
                ('patronymic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonebook.personpatronymic', verbose_name='Отчество')),
                ('surname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonebook.personsurname', verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
                'ordering': ['surname', 'name', 'patronymic'],
            },
        ),
    ]
